version: '3.8'
services:
  db:
    image: postgres:16
    container_name: marathon-db
    environment:
      POSTGRES_DB: skopjemarathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6vNb9PZb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: skopje-marathon-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    depends_on:
      - db

volumes:
  db_data:
